const express = require('express')
const router = express.Router()
const User = require('../controllers/userController')
const weibo = require('../controllers/weiboController')
const upImage = require('../controllers/image')
const path = require('path')
const multer = require('multer')
const uploads = multer({ dest: path.join(__dirname, '../public/uploads') }).single('file')
router.get('/', User.getUser)
router.get('/getUserId', User.getUserId)
router.post('/Login', User.Login)
router.post('/user/EmailCode', User.EmailCode)
router.post('/user/isemail', User.isemail)
router.post('/user/register', User.register)
router.post('/user/userData', User.userData)
router.post('/user/userWeibo', User.userWeibo)
router.post('/upswiperimage', uploads, upImage.upSwiperImage)
router.get('/seewiperimgage', upImage.seeSwiperImage)
router.post('/delwiperimgage', upImage.delSwiperImage)
router.post('/newUpSwiperImage', upImage.newUpSwiperImage)
// 个人界面读取用户资料接口
router.post('/user/getuser', User.getuser)
router.post('/weibo/weiboHome', weibo.weiboHome)
router.post('/weibo/addlove', weibo.addweibolove)
router.post('/weibo/dellove', weibo.delweibolove)
router.post('/weibo/loveHome', weibo.loveHome)
router.post('/weibo/weibolist', weibo.weibolist)
router.post('/weibo/weibolove', weibo.weibolove)
router.post('/weibo/personalweibo', weibo.personalweibo)
router.post('/weibo/weiboforword', weibo.weiboforword)
router.post('/weibo/followuser', weibo.followuser)
module.exports = router
